### ISSUE TITLE
branch docker-1.13 needs update

### ISSUE THREAD

**Issue by runcom** [projectatomic/runc#4]
@mrunalp could you please rebase and re-push docker-1.13 branch? It must be rebased against `github.com/docker/runc` commit https://github.com/docker/docker/blob/v1.13.0-rc2/hack/dockerfile/binaries-commits#L4 (NOTE: we're not using opencontainers/runc as the base, but docker/runc!!!)

**Comment by runcom** [comment]
ping @mrunalp, I'm about to rebuild docker-1.13 in docker-latest in Rawhide, could you take care of this one?

**Comment by mrunalp** [comment]
Yeah, I'll take care of this.

**Comment by mrunalp** [comment]
We don't need to carry the tmpfs copy up commits as they are present already. We do however need the fix for mqueue which will take some time to rework. I will create the PR upstream as it will be the same fix. Meanwhile I have pushed docker-1.13 to same commit as docker/runc. I will update once I have a PR for mqueue ready.

**Comment by runcom** [comment]
Great, thanks @mrunalp, let me know once ready (no rush at all though!)

**Comment by runcom** [comment]
@mrunalp branch docker-1.13 is setup to track docker/runc to go along with docker-1.13, we just need that mqueue+selinux patch backported to this new docker-1.13 branch. After that, I'll kick out builds for Rawhide and docker-latest in F25

**Comment by mrunalp** [comment]
I started porting this but running into mount of tmpfs failing when a context is passed under user namespaces. @rhatdan was following up with upstream kernel about this.

**Comment by rhatdan** [comment]
This is fixed in kernels being proposed for upstream.  Not sure if it has made it into a release candidate yet.

**Comment by mrunalp** [comment]
We can close this now as #5 is merged.
